-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 13:41:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_review_film
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_review_film
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_review_film` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_review_film` ;

-- -----------------------------------------------------
-- Table `db_review_film`.`casts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`casts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `biodata` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `year` YEAR NULL DEFAULT NULL,
  `poster` VARCHAR(255) NULL DEFAULT NULL COMMENT 'URL atau path ke file gambar poster',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`movie_casts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`movie_casts` (
  `movie_id` INT NOT NULL,
  `cast_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `cast_id`, `role_id`),
  INDEX `cast_id` (`cast_id` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `movie_casts_ibfk_1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_review_film`.`movies` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `movie_casts_ibfk_2`
    FOREIGN KEY (`cast_id`)
    REFERENCES `db_review_film`.`casts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `movie_casts_ibfk_3`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_review_film`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`movie_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`movie_genres` (
  `movie_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `genre_id`),
  INDEX `genre_id` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `movie_genres_ibfk_1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_review_film`.`movies` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `movie_genres_ibfk_2`
    FOREIGN KEY (`genre_id`)
    REFERENCES `db_review_film`.`genres` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `biodata` TEXT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `profiles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_review_film`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_film`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_film`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `rating` INT NOT NULL,
  `critics` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `movie_id` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_review_film`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_review_film`.`movies` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
